### ISSUE TITLE
v8 Debugger

### ISSUE THREAD

**Issue by MylesBorins** [jasnell/vm-summit#7]
From https://github.com/nodejs/node/issues/7072

> Current status: v8_inspector support has been merged in to master @ #6792, as yet it's not in v6.x but I'm anticipating that it soon will be. 
> @rvagg 

There are some hanging questions regarding the new v8 debugger. It is important to get the input of various vm stakeholders including the individuals working Chakracore (@kunalspathak ), Spidernode (@ehsan), v8 (@ofrobots), and Node core.

I've started an [issue in the tracing wg](https://github.com/nodejs/tracing-wg/issues/51) to start the conversation, perhaps the work should take place there, perhaps in a separate debugging wg. Either way it is very important to have the involvement of the stakeholders mentioned above in the conversation.

The purpose of this issue is to raise awareness to those following this repo, and perhaps serve a a channel to collect thoughts before bringing them to a larger working group setting.

**Comment by kunalspathak** [comment]
// Including @Agarwal-Sandeep who is working on debugger for node+chakracore.
